create table product_category
(
    id            bigint generated by default as identity,
    category_name varchar(255),
    primary key (id)
);

create table products
(
    prod_id      bigint generated by default as identity,
    product_name varchar(255) not null,
    price        double       not null,
    productid    bigint       not null,
    primary key (prod_id)
);

alter table products
    add constraint product_category_fk foreign key (productid) references product_category;